### ISSUE TITLE
Different rent users are forbidden from uploading the same resource file

### ISSUE THREAD

**Issue by hyperknob** [analysys/EasyScheduler#101]
Different rent users are forbidden from uploading the same resource file, I think this is only a functional enhancement issue, so track it here. Thx.

**Comment by lidongdai** [comment]
We will record the number of partners with this requirement. If the partners have the same needs, please reply “+1”

我们将记录有此需求的伙伴数量，如果别的伙伴们有同样的需求，请回复+1
