### ISSUE TITLE
sudo unknown user :test

### ISSUE THREAD

**Issue by samz406** [analysys/EasyScheduler#105]
写了一个简单的shell任务。执行时报下面的错误
![image](https://user-images.githubusercontent.com/3055810/56550465-46ef8180-65b8-11e9-970f-7bce9b8e11e7.png)

这个test是怎么出来的？

**Comment by lidongdai** [comment]
@lgcareer Please deal with user this issue! thx!

**Comment by lidongdai** [comment]
please give more worker-server runtime log information!  It's likely create tenant not success!

使用的租户名是什么？用户名？

**Comment by samz406** [comment]
看了源码发现是这里用户是租户code。所以这里test是租户code，改下租户code 就好了。
