### ISSUE TITLE
Implement a small distributed file system (supporting stand-alone) for resource uploading instead of hdfs.    

### ISSUE THREAD

**Issue by lidongdai** [analysys/EasyScheduler#106]
Implement a small distributed file system (supporting stand-alone) for resource uploading instead of hdfs.    

实现一个小巧的分布式文件系统(支持单机)，用于资源上传，替代hdfs

**Comment by Baoqi** [comment]
I would suggest use https://github.com/minio/minio to replace HDFS, since:
   1. it is relatively easy. and it implements AWS S3 API
   2. it also have wrapper around common fs, like, AWS, azure, even HDFS

**Comment by lzy305** [comment]
+1

**Comment by RustRw** [comment]
https://github.com/sjqzhang/go-fastdfs  扩容简单,  支持断点续传等.

**Comment by Davidsong1989** [comment]
+1

**Comment by Baoqi** [comment]
Details information about how to use HDFS/ Local FileSystem / AWS S3 (or Minio Server), please see pull request https://github.com/analysys/EasyScheduler/pull/267

**Comment by sudddenly** [comment]
这个单机版本可以用吗？具体怎么用呢？

**Comment by Baoqi** [comment]
> 这个单机版本可以用吗？具体怎么用呢？

Yes, please refer to https://github.com/apache/incubator-dolphinscheduler/pull/267 for the detailed usage. Especially part 3, how to use with Minio . 

Note: that was based on dev-1.1.0 branch,  but in the newest 1.2.0 branch, the configuration files may be in different location, please double check.
