### ISSUE TITLE
前端UI部署文档是不是有问题？

### ISSUE THREAD

**Issue by sherlock111** [analysys/EasyScheduler#111]
https://analysys.github.io/easyscheduler_docs_cn/%E5%89%8D%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.html#1%E3%80%81%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

这个手册，目的就是安装一个Nginx , 配置nginx 前台访问端口8888， 后台代理端口12345，目录指向dist。
1、
按照这个思想，我下载安装了Nginx ，严格按照部署手册配置，
访问http://10**:8888 时候 报错，会自动访问如下这个URL，404错误
http://10***:8888/escheduler/users/get-user-info?_t=0.06944380999772859
404 Not Found

2、
 后台代理端口12345 这个是约定跟后台交互的端口还是怎样？
因为在安装 eschedule后台的时候，一键启动，并没有涉及代理端口

**Comment by millionfor** [comment]
你好，
1.安装完成之后自动根据get-user-info接口返回信息是否登录来跳转页面，检查下后端是否部署成功
2. 12345是前端与后端约定的交互端口，也可以在配置自行修改 可加群详聊

**Comment by datuzi** [comment]
> https://analysys.github.io/easyscheduler_docs_cn/%E5%89%8D%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.html#1%E3%80%81%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C
> 
> 这个手册，目的就是安装一个Nginx , 配置nginx 前台访问端口8888， 后台代理端口12345，目录指向dist。
> 1、
> 按照这个思想，我下载安装了Nginx ，严格按照部署手册配置，
> 访问http://10**:8888 时候 报错，会自动访问如下这个URL，404错误
> http://10***:8888/escheduler/users/get-user-info?_t=0.06944380999772859
> 404 Not Found
> 
> 2、
> 后台代理端口12345 这个是约定跟后台交互的端口还是怎样？
> 因为在安装 eschedule后台的时候，一键启动，并没有涉及代理端口

查看nginx日志中报的错，如果是没有权限访问XX文件，查看nginx.conf中user是否正确。

**Comment by sherlock111** [comment]
我的问题，多了一个=号，大家在配置nginx.conf的时候眼睛要睁大。
非常不好意思。谢谢支持。
