### ISSUE TITLE
call datax failure （调用datax失败）

### ISSUE THREAD

**Issue by swxchappy** [analysys/EasyScheduler#113]
![image](https://user-images.githubusercontent.com/36871730/56568840-669f9d80-65ea-11e9-82ed-464989540fd9.png)
[INFO] 2019-04-23 17:06:58.862 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_42_159_699]  -> 
	DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
	Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
	
	
	/bin/sh: java: command not found

**Comment by lidongdai** [comment]
please show the content of  ".escheduler_env.sh", It's in the “conf/env” directory
> `ll -a`
![image](https://user-images.githubusercontent.com/48329107/56627302-c98b4600-6677-11e9-89c7-4ca07c7efb14.png)

It's likely JAVA_HOME is not config rightly!
