### ISSUE TITLE
 escheduler-daemon.sh无法识别JAVA_HOME导致安装失败

### ISSUE THREAD

**Issue by chubbyjiang** [analysys/EasyScheduler#119]
错误信息：
```shell
cat escheduler-api-server-host1.out
nohup: 无法运行命令"/bin/java": 没有那个文件或目录
```

JAVA_HOME在shell环境中可以获取到。
```shell
echo $JAVA_HOME
/usr/java/jdk1.8.0
```

临时解决方案：
**在文件 escheduler-daemon.sh 写死export JAVA_HOME=xxx**

期望能有个比较优雅的方式解决这个问题，比如：
**.escheduler_env.sh文件已手动指定环境变量信息，escheduler-daemon.sh可直接复用。**

**Comment by lidongdai** [comment]
good idea, we will use .escheduler_env.sh 
and fix it in version 1.0.2

**Comment by KennCai** [comment]
it's not resolved in version 1.2.0. 
You need to add command “source $DOLPHINSCHEDULER_HOME/conf/env/.dolphinscheduler_env.sh” to dolphinscheduler-daemon.sh before Export $JAVA_HOME.
