### ISSUE TITLE
Escheduler backend service startup error （escheduler 后台启动报错）

### ISSUE THREAD

**Issue by kevin5210** [analysys/EasyScheduler#124]
[root@bogon escheduler-backend-1.0.1]# sh install.sh 
1,替换文件
2,创建目录
root@10.23.8.203's password: 
root@10.23.8.203's password: 
root@10.23.8.203's password: 
root@10.23.8.203's password: 
3,停止服务
ssh: Could not resolve hostname cd /; sh bin/escheduler-daemon.sh stop alert-server;: Name or service not known
4,删除zk节点
deleted success
5,scp资源
scp拷贝完成
6,启动
ssh: Could not resolve hostname cd /; sh bin/escheduler-daemon.sh start alert-server;: Name or service not known

附文件配置：
# conf/config/install_config.conf配置
# 安装路径,不要当前路径(pwd)一样
installPath="/usr/local/escheduler-backend-1.0.1"

escheduler路径：
[root@bogon bin]# pwd
/usr/local/escheduler-backend-1.0.1/bin
[root@bogon bin]# ls
escheduler-daemon.sh
[root@bogon bin]#

**Comment by kevin5210** [comment]
@dailidong 帮忙指导一下

**Comment by lidongdai** [comment]
can you show the result 
> hostname -i

**Comment by dailidong** [comment]
Please follow the steps in the documentation: [Deployment document
](https://analysys.github.io/easyscheduler_docs_cn/%E5%90%8E%E7%AB%AF%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.html)

**Comment by dailidong** [comment]
if have problems again，please contact us， close this issue for now！
