### ISSUE TITLE
租户管理中，租户编码带下划线等特殊字符无法通过校验

### ISSUE THREAD

**Issue by chubbyjiang** [analysys/EasyScheduler#129]
按照设定，租户编码=linux用户名，当linux用户名带下划线等特殊字符时，创建租户会提示【请输入英文租户编码】。

临时解决方案：直接修改对应数据库表t_escheduler_tenant的内容。

期望：前端校验逻辑可以优化下，允许特殊字符的情况。

**Comment by lidongdai** [comment]
thx!  we will fix it in version 1.0.2

**Comment by lidongdai** [comment]
#154
