### ISSUE TITLE
Task type support Oracle、CLICKHOUSE、SQLSERVER （任务类型支持 Oracle、CLICKHOUSE、SQLSERVER）

### ISSUE THREAD

**Issue by lidongdai** [analysys/EasyScheduler#134]

**Comment by lidongdai** [comment]
@Baoqi  @lgcareer  verify and test !

**Comment by Baoqi** [comment]
I have tested and used in my local environment to connect and execute sql on  Oracle、CLICKHOUSE、SQLSERVER. 

Though, for Oracle, don't forget to manually download the jdbc drivers and put into /lib folder.

**Comment by lidongdai** [comment]
very good!
