### ISSUE TITLE
关于给EasyScheduler的一些建议，仅供参考。

### ISSUE THREAD

**Issue by datuzi** [analysys/EasyScheduler#143]
1.租户删除前可以考虑校验租户和资源是否存在关联关系，如果有，删除时候，报错提示出来关联项。
2.工作流同上。
3.租户编码可以考虑在前端把限制规则调整一下，允许纯数字或者下划线这种的编码。
4.涉及数据源密码的地方需要加密，如数据源测试连接日志、工作流运行日志、查看数据源、元数据表中连接参数中密码信息，以提高系统安全性。
5.如果可以支持hplsql更好，就可以在hive/impala/other上执行类似关系型数据上的存储过程；这样对于有特殊需求的用户来说，比如用户想对某个表（开启更新的hive orc表或者kudu表）的每一条记录进行处理，处理规则是不同的，存储过程里的游标就可以满足类似功能。

**Comment by lidongdai** [comment]
Thank you for your very pertinent advice.
We will split these tasks to five detail task!

thx!
