### ISSUE TITLE
缺少LogParameter和RetStrInfo

### ISSUE THREAD

**Issue by qq389401879** [analysys/EasyScheduler#15]
LogViewServiceGrpc 下面找不到LogParameter和RetStrInfo

**Comment by lidongdai** [comment]
please compile project first use this command:

> mvn -U clean package assembly:assembly -Dmaven.test.skip=true

then class LogParameter and RetStrInfo will generate by maven!

**Comment by lidongdai** [comment]
compile then you will find this:

![image](https://user-images.githubusercontent.com/48329107/55568844-15ab3080-5733-11e9-93c4-b5d3eb9eeead.png)

**Comment by qq389401879** [comment]
我其实是想用IDEA开发模式跑起来，先不跑大数据相关的东西，就单纯跑JAVAWEB应用，该如何办呢？

**Comment by lenboo** [comment]
前端部署文档中有直接运行的脚本

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29528966/55695224-32bd5900-59ea-11e9-8d34-55594f72577b.png">

**Comment by dailidong** [comment]
I think compile according to the deployment documentation will be faster: https://analysys.github.io/easyscheduler_docs_cn/
