### ISSUE TITLE
导入项后运行escheduler-server直接报错

### ISSUE THREAD

**Issue by huanzui** [analysys/EasyScheduler#18]
![image](https://user-images.githubusercontent.com/7300261/55625502-945ba880-57db-11e9-97c6-5d9c21b9f784.png)
指示cn.escheduler.rpc中没有LogParameter等类

**Comment by lidongdai** [comment]
because use grpc，need compile first，reference：https://github.com/analysys/EasyScheduler/issues/15
#15

**Comment by huanzui** [comment]
刚看到了 ，谢谢

**Comment by dailidong** [comment]
> 刚看到了 ，谢谢

You are welcome
