### ISSUE TITLE
所有查询中只要输入%会返回所有数据

### ISSUE THREAD

**Issue by samz406** [analysys/EasyScheduler#186]
在有查询的地方输入%，都会返回所有结果，
`  WHERE( " p.name like concat('%', #{searchVal}, '%') ");`

向上面的拼接,最后就构造成, '%%%' 这样，就会查询所有结果。
解决办法是将%进行转义成普通字符。
可以通过加一个拦截器，对GET请求的参数校验下。有特殊字符就转义。

**Comment by qiaozhanwei** [comment]
1.0.3已经修复
