### ISSUE TITLE
编译UI报错。

### ISSUE THREAD

**Issue by datuzi** [analysys/EasyScheduler#208]
![image](https://user-images.githubusercontent.com/18095523/56857728-a926f880-69a3-11e9-98fb-a102df87a391.png)
请确认escheduler-ui\src\js\conf\home\pages\projects\pages\index\index.vue中第78行 CommandStateCount 是否应该是commandStateCount，修改成commandStateCount编译是成功的。

**Comment by millionfor** [comment]
不好意思 已修复

**Comment by dailidong** [comment]
good，close this issue for now！
