### ISSUE TITLE
工作流定义修改节点，locations字段未更新

### ISSUE THREAD

**Issue by samz406** [analysys/EasyScheduler#214]
创建一个工作流，预先定义三个节点，保存后再更新删除其中一个，其中的locations字段值未更新。还是存的最先三个节点坐标
![image](https://user-images.githubusercontent.com/3055810/56859893-873d6e00-69c3-11e9-811f-aa62b958f49e.png)

**Comment by millionfor** [comment]
你好，locations为大json提供节点位置信息，目前并不影响使用。此bug已修复
