### ISSUE TITLE
admin账户无法修改密码

### ISSUE THREAD

**Issue by telltime** [analysys/EasyScheduler#219]

**Comment by telltime** [comment]
版本1.0.2，全新部署，不是从旧版本升级过来的。其他信息创建修改都可以，admin账户密码修改报错。

**Comment by dailidong** [comment]
we need more information, please show api server log about this operation,thx!

**Comment by Heltman** [comment]
我安装1.2.1也不能修改管理员密码，提示request parameter xx is not valid

**Comment by wjf989** [comment]
> 
> 
> 我安装1.2.1也不能修改管理员密码，提示request parameter xx is not valid

我这边安装的版本是1.3.1，在进行修改管理原密码的时候，也是提示跟你同样的问题；后面通过F12，查询相应信息，发现这个错误是‘手机’这个信息产生影响的，你必须将该‘手机’参数修改为正确的格式，否则无法正常修改密码，如
![图片](https://user-images.githubusercontent.com/49484750/88007693-1abb0b80-cb41-11ea-8ae0-09fb08782e18.png)

**Comment by Heltman** [comment]
> > 我安装1.2.1也不能修改管理员密码，提示request parameter xx is not valid
> 
> 我这边安装的版本是1.3.1，在进行修改管理原密码的时候，也是提示跟你同样的问题；后面通过F12，查询相应信息，发现这个错误是‘手机’这个信息产生影响的，你必须将该‘手机’参数修改为正确的格式，否则无法正常修改密码，如
> ![图片](https://user-images.githubusercontent.com/49484750/88007828-62da2e00-cb41-11ea-8804-9ebaacc690e2.png)

1.2.1测试成功，多谢了！
