### ISSUE TITLE
对版本号的规范意见

### ISSUE THREAD

**Issue by fanguanqun** [analysys/EasyScheduler#228]
版本号提个意见，假如版本号为x.y.z  ,  当x增加时代表全新架构的版本。当y增加时代表与y版本之前的不兼容需要升级脚本或其他人工处理才能升级。当z增加代表是bug修复，升级完全兼容。无需额外处理。目前，1.0.2的升级就不兼容1.0.1需要升级脚本。按规范就应该到1.1.0了。这样规范一下，对用户比较友好。

**Comment by dailidong** [comment]
Thank you very much, we will adopt this specification in future releases.
