### ISSUE TITLE
I hope the DAG graph supports copying, exporting, and importing.(希望流程图支持复制、导出、导入)

### ISSUE THREAD

**Issue by fanguanqun** [analysys/EasyScheduler#233]
1, for the big data processing process, the process is almost the same, basically the data collection, data cleaning, data analysis statistics, indicator data export, the difference is part of the configuration of the link. If each new process is to be configured from the ground up, it is a bit cumbersome to use.
2. The configuration of the DAG graph is the key information of production. If it is changed, it needs a means of rapid restoration. So export to a text file, one can be backed up, but can be compared to the version to quickly find the difference. This quickly restores misuse.

---
1、对于大数据处理过程，流程其实都差不多，基本都是数据采集、数据清洗、数据分析统计、指标数据导出，差异的都是个环节的部分配置。如果每个新流程都要从头开始配置，使用上有些繁琐。
2、流程图的配置是生产的关键信息，被人改动了就需要有快速还原的手段。所以导出成文本文件，一是可以备份，而是可以做版本的比对快速发现差异。从而快速恢复误操作。

**Comment by dailidong** [comment]
Very good, look forward to your contribution to this issue (pr)

**Comment by qq389401879** [comment]
I want to implement this feature!

**Comment by boandai** [comment]
very good，thanks，looking forward to contributing code！

**Comment by dailidong** [comment]
exporting, and importing feature will be supported in the next version!

**Comment by dailidong** [comment]
pr #709

**Comment by chuyang-zl** [comment]
想问一下，这是哪个版本提供的功能，这点被列在了1.3.1 release Node中，但是1.2.1中ResourcesController中已有下载接口
