### ISSUE TITLE
创建spark数据源，点击“测试连接”，系统回退回到登入页面

### ISSUE THREAD

**Issue by fanguanqun** [analysys/EasyScheduler#235]
点击“测试连接”，系统回退回到登入页面，版本1.0.1
![spark](https://user-images.githubusercontent.com/35256314/56938142-d81fa480-6b32-11e9-8211-7434933f6640.png)

**Comment by dailidong** [comment]
has this issue been resolved? if resolved, please close this issue, thx!

**Comment by fanguanqun** [comment]
当数据源配置错误时，点击“测试连接”，系统回退回到登入页面。问题还存在。

**Comment by qq389401879** [comment]
不止是测试连接会闪退，是很多地方都会闪退，我就按照前后端最简单部署方式部署的。

**Comment by qiaozhanwei** [comment]
修改/etc/nginx/conf.d/escheduler.conf
            proxy_connect_timeout 300s;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
