### ISSUE TITLE
租户删除导致页面用户列表显示不出来

### ISSUE THREAD

**Issue by Davidsong1989** [analysys/EasyScheduler#257]
问题原因执行操作：
delete from  t_escheduler_tenant where tenant_code='xxxx';
导致：
页面用户列表显示不出来
需执行： update t_escheduler_user set tenant_id=3;用户列表才会显示

<img width="900" alt="image" src="https://user-images.githubusercontent.com/50355324/57278519-3a4f4b00-70d9-11e9-98a0-04cd9f84e8c0.png">

**Comment by qiaozhanwei** [comment]
首先我们现在是不支持租户删除的，故关联查询用的是=，没有使用left join
注意：
我们不建议个人直接修改数据库租户表，因为如果启动hdfs，租户编码会关联hdfs路径，一旦修改租户编码，用户资源将找不到。我们会在下一个版本支持租户删除，同时也会解决这个问题，最好请使用我们界面操作，谢谢。
