### ISSUE TITLE
运行工作流bug

### ISSUE THREAD

**Issue by itheima-cby** [analysys/EasyScheduler#259]
有时候运行工作流的时候工作流实例以及任务实例会没有显示最新的信息，同时worker日志以及master日志也是没有任何报错信息，多次重启或者重新安装问题仍然在，重启zookpeer也是同样存在，重启后，会显示重启之前运行的工作流实例相关信息，之前这个问题偶尔出现，最近这个问题经常出现，请问你们那边有遇到过吗？

**Comment by qiaozhanwei** [comment]
没有显示最新的信息是什么意思？没有听太懂。是没有运行最新的启动的流程定义，是吗？这样的话，可以看首页，command表的统计信息，或者看数据库t_escheduler_command或t_escheduler_error_command表里面的内容。

**Comment by itheima-cby** [comment]
感谢作者的回复，问题已经解决，是某台服务器上的进程杀掉过程中出问题，没有发现，导致没有master扫描command命令。




------------------ 原始邮件 ------------------
发件人: "乔占卫"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 下午4:43
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "小小先生"<821555203@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] 运行工作流bug (#259)




没有显示最新的信息是什么意思？没有听太懂。是没有运行最新的启动的流程定义，是吗？这样的话，可以看首页，command表的统计信息，或者看数据库t_escheduler_command或t_escheduler_error_command表里面的内容。

**Comment by dailidong** [comment]
ok，if resolved，close this issue for now
