### ISSUE TITLE
你好作者，我想请问一下，关于子流程类型无法运行的问题

### ISSUE THREAD

**Issue by cxyab** [analysys/EasyScheduler#260]
目前其他工作流类型都是可以的，创建工作流中包含了sub_process和其他类型的任务时，其他类型的任务能正常工作，完成，sub_process就一直处于提交成功的状态，t_escheduler_process_instance表中有数据，worker线程没有日志显示，想请问这一块的功能是已经测试通过的还是说还未完善？我的项目版本是4月24从master拉取下来的，在你们正式发布1.0.2之前的版本，期待作者的回复，谢谢

**Comment by lenboo** [comment]
Sub process function is test successfully, we need more information for this issue, for example: some images and logs.

**Comment by lenboo** [comment]
The master handles commands. Work process runs by adding a new command, and so does the sub-workflow. If the master has errors, it is likely that the command of the sub-workflow is wrong.

**Comment by cxyab** [comment]
感谢回复，不过子流程不嵌套在其他工作流程中时，是可以运行的，里面的任务都是能够成功执行的




------------------ 原始邮件 ------------------
发件人: "bao liang"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午2:39
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "冰山☆詠遠愛"<1029942482@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] 你好作者，我想请问一下，关于子流程类型无法运行的问题 (#260)




The master handles commands. Work process runs by adding a new command, and so does the sub-workflow. If the master has errors, it is likely that the command of the sub-workflow is wrong.

**Comment by lenboo** [comment]
can you post the master's error log?  it will be helpful for solving this issue.

**Comment by cxyab** [comment]
可以，我直接回复邮件，照片附在邮件中，github中可能看不到，这是一个工作流，里面有两个task任务，如下图，名称为子流程的task是一个子流程，运行时报如下错误









------------------ 原始邮件 ------------------
发件人: "bao liang"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午2:58
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "冰山☆詠遠愛"<1029942482@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] 你好作者，我想请问一下，关于子流程类型无法运行的问题 (#260)




can you post the master's error log?  it will be helpful for solving this issue.

**Comment by cxyab** [comment]
好的，这是一个工作流，里面有两个task任务，如下图，名称为子流程的task是一个子流程，运行时报如下错误
![0](https://user-images.githubusercontent.com/50397013/57435642-7668e400-7270-11e9-8b82-85f167e89566.jpg)
![1](https://user-images.githubusercontent.com/50397013/57435652-7cf75b80-7270-11e9-909f-8ae305668a1f.jpg)
![2](https://user-images.githubusercontent.com/50397013/57435672-8aace100-7270-11e9-840b-ff800d455899.jpg)

**Comment by lenboo** [comment]
the errors are due to data structure not matched with data base.
because of some misoperations, the code in master on Apr.24 is unstable.
We recommend that you upgrade to version 1.0.2 that would be stronger.

**Comment by cxyab** [comment]
好的谢谢，我将尝试最新的




------------------ 原始邮件 ------------------
发件人: "bao liang"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午5:51
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "冰山☆詠遠愛"<1029942482@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [analysys/EasyScheduler] 你好作者，我想请问一下，关于子流程类型无法运行的问题 (#260)




the errors are due to data structure not matched with data base.
 because of some misoperations, the code in master on Apr.24 is unstable.
 We recommend that you upgrade to version 1.0.2 that would be stronger.
