### ISSUE TITLE
worker register 127.0.0.1 problem

### ISSUE THREAD

**Issue by feloxx** [analysys/EasyScheduler#286]
**Describe the bug**
worker register 127.0.0.1
IP cannot be recognized by the task, the program cannot be executed

**To Reproduce**

1. environment:
Linux 10-10-56-138 2.6.32-642.3.1.el6.centos.plus.x86_64;
CentOS release 6.6;
Front-end backend on the same device;
Use Local storage;

2. start:
sh ./bin/start_all.sh 

3. worker grouping
Create a new work group, ip is 192.168.10.101

4. Task uses this grouping
Running error: task instance does not set host

5. Found worker and tasker configuration
All registered as 127.0.0.1, but my installation configuration is 192.168.10.101

**Expected behavior**
The program cannot be executed

**Screenshots**

![2444](https://user-images.githubusercontent.com/8359848/57668267-661e8380-7639-11e9-810f-d46259099aa8.jpeg)
![2312](https://user-images.githubusercontent.com/8359848/57668268-661e8380-7639-11e9-838e-9182a40f979e.jpeg)

**Comment by lidongdai** [comment]
@feloxx ， could you submit a pr to resolve this bug?

 thx!

**Comment by qiaozhanwei** [comment]
如果对于ip是127.0.0.1的情况，可能是测试环境   原始的配置：
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4                                                                                                               
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
解决方法两种方式：
1，127.0.0.1 修改成你真实ip
2，修改linux主机名称，将真实的Ip和hostname对应起来

**Comment by BongBongBang** [comment]
目前Dolphin只支持注册hostname到zookeeper吗？这样子就必须要配置相应的hostname才行了。可以配置注册服务器ip到zookeeper吗？

**Comment by wllzhang** [comment]
> 目前Dolphin只支持注册hostname到zookeeper吗？这样子就必须要配置相应的hostname才行了。可以配置注册服务器ip到zookeeper吗？

I meet the same problem.
