### ISSUE TITLE
启动api server时报错 

### ISSUE THREAD

**Issue by hyperknob** [analysys/EasyScheduler#29]
启动api server时报错 class "javax.servlet.http.HttpSessionIdListener"'s signer information does not match signer information of other classes in the same package ， 但是检查lib目录下又没有重复的HttpSessionIdListener.class，何解？

**Comment by free-souls** [comment]
> 使用openjdk编译会有如上问题，最好采取oracle jdk 1.8。另外，本人把parent pom下的hadoop-common和hive-jdbc的servlet-api排除掉了。试验通过。

把parent pom下的hadoop-common和hive-jdbc的servlet-api排除掉了. 这种我这里测试没有成功，还是一样的错误

**Comment by free-souls** [comment]
将lib包下的servlet-api-2.5-6.1.14.jar 和 javax.servlet-3.0.0.v201112011016.jar这两个包删除掉，可以成功启动

**Comment by qiaozhanwei** [comment]
[root@Redis-4 lib]# ls | grep "servlet*"
guice-servlet-3.0.jar
javax.servlet-3.0.0.v201112011016.jar
javax.servlet-api-3.1.0.jar
jetty-servlet-9.3.16.v20170120.jar
jetty-servlets-9.3.16.v20170120.jar
servlet-api-2.5-6.1.14.jar

note : delete javax.servlet-3.0.0.v201112011016.jar and servlet-api-2.5-6.1.14.jar resolve servlet conflicts



[root@Redis-4 lib]# ls | grep "protobuf"
grpc-protobuf-1.9.0.jar
grpc-protobuf-lite-1.9.0.jar
protobuf-java-2.5.0.jar
protobuf-java-3.5.1.jar
protobuf-java-util-3.5.1.jar

note : delete protobuf-java-2.5.0.jar resolve gRPC conflicts
