### ISSUE TITLE
test connect data source timeout and redirect to login

### ISSUE THREAD

**Issue by lenboo** [analysys/EasyScheduler#297]
it would be redirected to login page if the  ip address is unconnected when creating a new data source.

**Comment by qiaozhanwei** [comment]
nginx超时引起的，已修复

**Comment by lenboo** [comment]
在nginx配置中修改超时配置：

        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
