### ISSUE TITLE
建议数据源不强制指定数据库名字

### ISSUE THREAD

**Issue by leiruiqi** [analysys/EasyScheduler#307]
数据处理，经常有夸db的场景.
比如：
1、mysql中，统计表和业务表可能在同一个实例的不同库下（当然这个套路不专业）。统计需要用到 insert into db1.table1 select db2.table2。或者需要关联查询。
2、hive中，不同层级的库和表，数据分析都会用到。

如果数据源不强制限制库，一个sql任务就能完成业务或者数据分析。

**Comment by lidongdai** [comment]
very good！thx！
could you submit a pull request for this issue？

**Comment by lgcareer** [comment]
Cross-database support is currently supported!Specify that the database is just a test connection!
