### ISSUE TITLE
更多的数据源支持

### ISSUE THREAD

**Issue by cmdares** [analysys/EasyScheduler#34]
能否支持oracle，希望支持主流数据库。同时希望通过jdbc的方式，支持更多的数据库。至于存储过程这块，可以使用jdbc标准的存储过程的调用方法。感谢。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dailidong** [comment]
Versions released at the end of this month will support oracle、clickhouse！ if need more databases, please tell us! 

thank you!

**Comment by cmdares** [comment]
感谢回复！
如果需要罗列的话，希望支持大数据和关系库的主流数据
1、greenplum
2、clickhouse
3、mysql、oracle、postgresql、sqlserver
4、hive、spark
5、标准jdbc的通用数据库

**Comment by huanzui** [comment]
> 感谢回复！
> 如果需要罗列的话，希望支持大数据和关系库的主流数据
> 1、greenplum
> 2、clickhouse
> 3、mysql、oracle、postgresql、sqlserver
> 4、hive、spark
> 5、标准jdbc的通用数据库

还需要http类型的和 ES、mongodb的

**Comment by lidongdai** [comment]
EasyScheduler support  MYSQL、POSTGRESQL、 HIVE/IMPALA、SPARK、CLICKHOUSE、ORACLE   SQLSERVER for now，We will implement plugin mechanism for more task type in the future！

**Comment by qulibibg** [comment]
Greenplum和pg很像啊，可以直接连吗？

**Comment by davidzollo** [comment]
> Greenplum和pg很像啊，可以直接连吗？
@qulibibg, of course

**Comment by gaogen123** [comment]
we ran into a lot of problems when running Greenplum  procedures and dataX tasks concurrently with the postgresql driver in DS.Such as the connection is interrupted during the task running or Other driving problems and so on.

**Comment by gaogen123** [comment]
can you support  greenplum in next release
