### ISSUE TITLE
上传比较大的文件卡住

### ISSUE THREAD

**Issue by itheima-cby** [analysys/EasyScheduler#341]
**Describe the bug**
上传txt文件到linux上，如果文件比较小只有几kb,能够快速上传，但是上传几十上百kb大小的txt文本，页面显示上传100%，然后一直保持不动，卡住，后台没有真的上传成功，刷新后成功的列表中也没有相关文件！

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21357069/58231400-805b0e80-7d69-11e9-8107-7f37b06a95df.png)

**Additional context**

**Comment by dailidong** [comment]
which brower do you use?

**Comment by qiaozhanwei** [comment]
如果使用的是nginx，设置上传大小
编辑配置文件 vi /etc/nginx/nginx.conf
# 更改上传大小
client_max_body_size 1024m

**Comment by qiaozhanwei** [comment]
如果使用的是nginx，设置上传大小
编辑配置文件 vi /etc/nginx/nginx.conf

更改上传大小
client_max_body_size 1024m

**Comment by itheima-cby** [comment]
感谢回复，问题已经解决，是谷歌浏览器版本比较旧，更新了浏览器最新版就支持了
------------------ 原始邮件 ------------------
发件人: "乔占卫"<notifications@github.com>;
发送时间: 2019年5月24日(星期五) 下午5:25
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "小小先生"<821555203@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [analysys/EasyScheduler] 上传比较大的文件卡住 (#341)




如果使用的是nginx，设置上传大小
 编辑配置文件 vi /etc/nginx/nginx.conf
 
更改上传大小
 client_max_body_size 1024m

**Comment by dailidong** [comment]
very good, thx

**Comment by xwhfcenter** [comment]
well done, thanks
