### ISSUE TITLE
worker 分组, 队列消费问题

### ISSUE THREAD

**Issue by hujiang75277381** [analysys/EasyScheduler#352]
worker A（只能处理A类型的任务），worker B（只能处理B类型的任务），此时 队列中存在 A B C 三个类型的任务，需要跳过C 去消费 B 和A

**Comment by dailidong** [comment]
good idea, we will improve it later! thx!

**Comment by hujiang75277381** [comment]
我通过我自己的方式,把这个问题处理了。
1.在processDao.taskZkInfo（954行） 中添加task的类型，形成 
  task类型_流程实例优先级_流程实例id_任务优先级_任务id 。

2.在taskQueueZkImpl.poll(141行) ，判断当前worker能处理那些task类型，如果不支持就丢弃。
把 task类型 taskId 中去掉，做优先级比较。

**Comment by dailidong** [comment]
we handle it by  "${processInstancePriority}_${processInstanceId}_${taskInstancePriority}_${taskId}_host1,host2,...", add task can execute on hosts at the end

**Comment by dailidong** [comment]
when taskQueueZkImpl.poll，worker will hold its ip to match， if can match ，the task will take
