### ISSUE TITLE
Mailbox regular match(邮箱正则匹配)

### ISSUE THREAD

**Issue by thisnew** [analysys/EasyScheduler#378]
esceduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js

In the isMail method

Regular missing match "-" symbol
  Such as nzy-666@126.com
The source code is let regEmail = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9 ]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable-line

Should be changed to let regEmail = /^([a-zA-Z0-9]+[_|\-|\_|\.]?)*[a-zA-Z0-9]+@([a-zA -Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable- line

---
escheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js

isMail方法中

正则  缺少匹配 “-” 符号
 如 nzy-666@126.com
源码为   let regEmail = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable-line

应改为  let regEmail = /^([a-zA-Z0-9]+[_|\-|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable-line

**Comment by dailidong** [comment]
very good！

could you submit a pull request ？ thx！
please refer ：https://github.com/analysys/EasyScheduler/wiki/EasyScheduler%E6%8F%90%E4%BA%A4%E4%BB%A3%E7%A0%81%E6%B5%81%E7%A8%8B
