### ISSUE TITLE
service monitor cannot find the change of master/worker

### ISSUE THREAD

**Issue by lenboo** [analysys/EasyScheduler#389]
首先kill -9 一个master 的服务,在另一台机器上启动master, 监控中心会显示两个master.

**Comment by hujiang75277381** [comment]
导航:监控中心/master/worker监控
问题:端口描述不准确,值是启动进程的pid
建议:将"端口"修改为"pid"

**Comment by bailgot** [comment]
问题：kill -9 work 节点，zk上work 已经是空的。master 日志 打印 work failover end .  但是前端故障work 没有状态 标识 节点下线
建议：建议添加work 状态标记或者直接去掉已经故障的work
