### ISSUE TITLE
Support Oracle,CLICKHOUSE

### ISSUE THREAD

**Issue by lzy305** [analysys/EasyScheduler#4]
希望支持可以调用oracle存储过程,SQL. 因为在很多传统行业。oracle数据库还是很多。

支持clickhouse sql.

**Comment by qiaozhanwei** [comment]
您的提议我们已经列入开发计划中，敬请关注我们的版本更新，如有其它问题请提issues或添加我们微信：510570367 谢谢！

**Comment by lidongdai** [comment]
Thank you very much for your advice. It has been included in the development plan, temporarily close the issue. Please pay attention for our version  updates!
