### ISSUE TITLE
停止工作流，并不能停止任务进程 (任务进程是常驻类型)

### ISSUE THREAD

**Issue by sunnyingit** [analysys/EasyScheduler#425]
启动es 进程：

这个进程会启动一个work 进程， work进程执行shell 任务，shell任务是一个常驻进程，它会创建自己的子进程。

停止es的进程，会kill掉worker进程，但是不会kill  shell 任务创建的子进程

**Comment by qiaozhanwei** [comment]
会在即将发布的1.0.3之后的小版本中修复这个问题
