### ISSUE TITLE
worker节点数量 zk和mysql中不一致

### ISSUE THREAD

**Issue by Stanfan** [analysys/EasyScheduler#434]
![1](https://user-images.githubusercontent.com/6930421/59018391-5ed54900-8878-11e9-846f-77d31df04b43.png)
![2](https://user-images.githubusercontent.com/6930421/59018392-5ed54900-8878-11e9-9ecd-27a01579da78.png)
如上图所示，配置文件中注册了3个worker节点，zk中显示三个，mysql中只显示一个。使用版本为1.0.3

**Comment by qiaozhanwei** [comment]
这个是由于非正常停止master和worker，不走钩子函数引起的。我们将在1.1.0版本中修复这个问题

**Comment by Stanfan** [comment]
请问有没有临时解决办法？

**Comment by qiaozhanwei** [comment]
这个是从mysql中获取的，可以直接从zk中获取就是最准的，还有一种方法可以看mysql last_heartbeat_time时间来判断，如果长时间没有心跳更新，那就是掉了。

**Comment by Stanfan** [comment]
嗯嗯，这是修复问题的思路，我的意思是我想先临时解决我这边的问题，有没有好的建议，比如重启项目？或者重建数据库？谢谢

**Comment by qiaozhanwei** [comment]
目前我们这想到的就是这样解决，没有更好的方法

**Comment by dailidong** [comment]
> 目前我们这想到的就是这样解决，没有更好的方法
临时解决方案：
如果是master掉的话，可以把t_escheduler_master_server表里旧的master数据删掉

如果是worker掉的话，可以把t_escheduler_worker_server表里旧的worker数据删掉

**Comment by lenboo** [comment]
> 嗯嗯，这是修复问题的思路，我的意思是我想先临时解决我这边的问题，有没有好的建议，比如重启项目？或者重建数据库？谢谢

很抱歉，这个问题我们需要更多环境和日志的支持，才能看到问题所在。
正常注册流程是
master/worker启动 -> 注册zk目录 -> 添加mysql记录。

你这个问题感觉是添加mysql没有成功，可以重启一下worker服务试试。

**Comment by Stanfan** [comment]
感谢楼上各位，我这边的问题已经定位到了，是因为worker节点访问mysql的账号权限不足导致的，已经解决了，谢谢。
