### ISSUE TITLE
if the node of worker run in platform at windows has error

### ISSUE THREAD

**Issue by mnloveyx** [analysys/EasyScheduler#451]
if the node of worker run in platform at windows has error,if the flow node is shell command,the SQL node also to error
![image](https://user-images.githubusercontent.com/20296448/59406798-ede6e180-8de1-11e9-9040-d9ed4f3a678d.png)

**Comment by lidongdai** [comment]
sorry, Easy Scheduler not support windows for now, please use ubuntu、centos、mac

**Comment by mnloveyx** [comment]
then how to debug or Dev for windows platform Developer

**Comment by lidongdai** [comment]
please use ubuntu or mac for now ,  we will support windows later
