### ISSUE TITLE
查看数据源参数，需要加密账号密码信息

### ISSUE THREAD

**Issue by telltime** [analysys/EasyScheduler#461]
![QQ截图20190616171119](https://user-images.githubusercontent.com/23161557/59562020-cb5efd80-9059-11e9-99fd-8e8a7b25b429.png)

数据源中心，数据源参数，点击查看，账号，密码，连接字符串式明文显示的，密码能否加密，或者不显示账号，密码

**Comment by dailidong** [comment]
very good！ thx!
 #146 

we will fix it in version 1.1.0!

**Comment by boandai** [comment]
pr #543  fix this issue!
