### ISSUE TITLE
邮箱验证不支持非常见后缀邮箱

### ISSUE THREAD

**Issue by telltime** [analysys/EasyScheduler#463]
![555555555](https://user-images.githubusercontent.com/23161557/59562090-ebdb8780-905a-11e9-806c-0d3e6de91a76.png)

邮箱验证不支持非常见后缀邮箱

**Comment by dailidong** [comment]
we will fix it in version 1.1.0, thx!

**Comment by lgcareer** [comment]
It's aleady resovled in version 1.1.0!
