### ISSUE TITLE
(deploy) user is not allowed to execute '/bin/sh /tmp/escheduler/exec/process

### ISSUE THREAD

**Issue by chinashenkai** [analysys/EasyScheduler#468]
[INFO] 2019-06-20 10:12:41.479 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_5_6]  -> Sorry, user escheduler is not allowed to execute '/bin/sh /tmp/escheduler/exec/process/1/1/4/5/1_4_5.command' as escheduler on 192.168.x.x.

**Comment by chinashenkai** [comment]
创建了租户 escheduler 之后使用租户 escheduler创建用户 test，使用test执行 shell 脚本程序出现了上面的错误。
[escheduler@node1 /opt/escheduler/logs]$ vim /opt/escheduler/logs/1/5/6.log
[INFO] 2019-06-20 10:12:41.479 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_5_6]  -> Sorry, user escheduler is not allowed to execute '/bin/sh /tmp/escheduler/exec/process/1/1/5/6/1_5_6.command' as escheduler on node1.

**Comment by chinashenkai** [comment]
vim escheduler-api-server.log




[INFO] 2019-06-20 10:21:34.834 cn.escheduler.api.controller.ExecutorController:[154] - login user test, get process definition receiver and cc
[INFO] 2019-06-20 10:21:34.834 cn.escheduler.api.service.ExecutorService:[373] - processInstanceId null
[INFO] 2019-06-20 10:21:36.825 cn.escheduler.api.service.SessionService:[69] - get session: 4784e8bd-49e2-4d67-a2d0-a1b25980e129, ip: 192.168.199.81
[INFO] 2019-06-20 10:21:36.828 cn.escheduler.api.controller.ExecutorController:[72] - login user test, start process instance, project name: 离线数仓测试, process definition id: 2, schedule time: , failure policy: CONTINUE, node name: TASK_POST, node dep: NONE, notify type: 0, notify group id: ,receivers:,receiversCc:RUN_MODE_SERIAL, run mode: MEDIUM,process instance priority:-1, workerGroupId: null, timeout: {}
[INFO] 2019-06-20 10:21:37.034 cn.escheduler.api.service.SessionService:[69] - get session: 4784e8bd-49e2-4d67-a2d0-a1b25980e129, ip: 192.168.199.81
[INFO] 2019-06-20 10:21:37.036 cn.escheduler.api.controller.ProcessDefinitionController:[234] - query proccess definition list paging, login user:test, project name:离线数仓测试
[INFO] 2019-06-20 10:21:39.683 cn.escheduler.api.service.SessionService:[69] - get session: 4784e8bd-49e2-4d67-a2d0-a1b25980e129, ip: 192.168.199.81
[INFO] 2019-06-20 10:21:39.686 cn.escheduler.api.controller.ProcessInstanceController:[74] - query all process instance list, login user:test,project name:离线数仓测试, define id:0,search value:,state type:null,host:,start time:, end time:,page number:1, page size:10
[INFO] 2019-06-20 10:21:53.769 cn.escheduler.api.service.SessionService:[69] - get session: 4784e8bd-49e2-4d67-a2d0-a1b25980e129, ip: 192.168.199.81
[INFO] 2019-06-20 10:21:53.772 cn.escheduler.api.controller.TaskInstanceController:[70] - query task instance list, project name:离线数仓测试,process instance:0, search value:,task name:null, state type:null, host:, start:, end:
[INFO] 2019-06-20 10:21:55.963 cn.escheduler.api.service.SessionService:[69] - get session: 4784e8bd-49e2-4d67-a2d0-a1b25980e129, ip: 192.168.199.81
[INFO] 2019-06-20 10:21:55.966 cn.escheduler.api.controller.LoggerController:[60] - login user test, view 7 task instance log ,skipLineNum 0 , limit 10000
[INFO] 2019-06-20 10:21:55.968 cn.escheduler.api.service.LoggerService:[57] - log host : 192.168.199.5 , logPath : /opt/escheduler/logs/2/6/7.log , logServer port : 50051
[INFO] 2019-06-20 10:21:55.969 cn.escheduler.api.log.LogClient:[79] - roll view log : path /opt/escheduler/logs/2/6/7.log,skipLineNum 0 ,limit 10000
[INFO] 2019-06-20 10:21:55.985 cn.escheduler.api.service.LoggerService:[65] - [INFO] 2019-06-20 10:21:40.171 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_7]  -> Sorry, user escheduler is not allowed to execute '/bin/sh /tmp/escheduler/exec/process/1/2/6/7/2_6_7.command' as escheduler on node1.^M

**Comment by chinashenkai** [comment]
vim escheduler-worker.log



[INFO] 2019-06-20 10:23:46.934 cn.escheduler.common.queue.TaskQueueZkImpl:[181] - consume task /escheduler/tasks_queue/2_6_2_9
[INFO] 2019-06-20 10:23:46.934 cn.escheduler.common.queue.TaskQueueZkImpl:[188] - consume task: 9,there still have 0 tasks need to be executed
[INFO] 2019-06-20 10:23:46.937 cn.escheduler.server.worker.runner.FetchTaskThread:[170] - worker fetch taskId : 9 from queue
[INFO] 2019-06-20 10:23:46.942 cn.escheduler.common.queue.TaskQueueZkImpl:[207] - consume task /escheduler/tasks_queue/2_6_2_9
[INFO] 2019-06-20 10:23:46.944 cn.escheduler.server.worker.runner.FetchTaskThread:[188] - remove task:2_6_2_9 from queue
[INFO] 2019-06-20 10:23:46.949 cn.escheduler.server.worker.runner.FetchTaskThread:[211] - task instance  local execute path : /tmp/escheduler/exec/process/1/2/6/9
[INFO] 2019-06-20 10:23:46.949 cn.escheduler.server.worker.runner.FetchTaskThread:[221] - task : 9 ready to submit to task scheduler thread
[INFO] 2019-06-20 10:23:46.954 cn.escheduler.server.worker.runner.TaskScheduleThread:[133] - script path : /tmp/escheduler/exec/process/1/2/6/9
[INFO] 2019-06-20 10:23:46.959 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] shell task params {"rawScript":"sh /start_run/123.sh","localParams":[],"resourceList":[]}
[INFO] 2019-06-20 10:23:46.962 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] raw script : sh /start_run/123.sh
[INFO] 2019-06-20 10:23:46.962 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] task dir : /tmp/escheduler/exec/process/1/2/6/9
[INFO] 2019-06-20 10:23:46.962 cn.escheduler.server.worker.log.TaskLogger:[183] - [taskAppId=TASK_2_6_9] tenantCode user:escheduler, task dir:2_6_9
[INFO] 2019-06-20 10:23:46.963 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] create command file:/tmp/escheduler/exec/process/1/2/6/9/2_6_9.command
[INFO] 2019-06-20 10:23:46.963 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/escheduler/conf/env/.escheduler_env.sh


/tmp/escheduler/exec/process/1/2/6/9/2_6_9_node.sh
[INFO] 2019-06-20 10:23:46.964 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] task run command:
sudo -u escheduler sh /tmp/escheduler/exec/process/1/2/6/9/2_6_9.command
[INFO] 2019-06-20 10:23:46.968 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] process start, process id is: 1762
[INFO] 2019-06-20 10:23:46.975 cn.escheduler.server.worker.log.TaskLogger:[188] - [taskAppId=TASK_2_6_9] process has exited, work dir:/tmp/escheduler/exec/process/1/2/6/9, pid:1762 ,exitStatusCode:1
[INFO] 2019-06-20 10:23:46.978 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_2_6_9] process id is 1762
[INFO] 2019-06-20 10:23:46.978 cn.escheduler.server.worker.runner.TaskScheduleThread:[198] - task : 2_6_9 exit status code : 1

**Comment by qiaozhanwei** [comment]
CentOS 还是 Ubuntu ?

**Comment by chinashenkai** [comment]
CentOS 7.

**Comment by chinashenkai** [comment]
发现问题了，
sudo -u escheduler sh /tmp/escheduler/exec/process/1/2/6/9/2_6_9.command
会报权限问题
sudo sudo -u escheduler sh /tmp/escheduler/exec/process/1/2/6/9/2_6_9.command 则可以正确执行。

**Comment by qiaozhanwei** [comment]
1，vi /etc/sudoers

# 例如部署用户是escheduler账号
escheduler  ALL=(ALL)       NOPASSWD: NOPASSWD: ALL

# 并且需要注释掉 Default requiretty 一行
#Default requiretty

#Default requiretty 这注释了吗？

2，这是通过install安装的，还是自己手动安装的？看你command权限，默认我们生成的都是有读和执行权限的

**Comment by qiaozhanwei** [comment]
1，vi /etc/sudoers

例如部署用户是escheduler账号
escheduler ALL=(ALL) NOPASSWD: NOPASSWD: ALL

并且需要注释掉 Default requiretty 一行
#Default requiretty

#Default requiretty 这注释了吗？

2，这是通过install安装的，还是自己手动安装的？看你command权限，默认我们生成的都是有读和执行权限的

**Comment by chinashenkai** [comment]
install安装的,
公司机器不允许加免密所有用户权限。
