### ISSUE TITLE
权限错误：任务执行时报错：Permission denied

### ISSUE THREAD

**Issue by antti8** [analysys/EasyScheduler#491]
配置了一个shell脚本任务，在执行的时候，报错如下：
`[INFO] 2019-06-26 20:11:29.774 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_4_3_3]  -> sh: /data/yananlin/soft/escheduler/exec/process/2/4/3/3/4_3_3.command: Permission denied
`
任务对应的脚本内容就是一个 echo "hello"
查看对应目录的所有者就是部署easyscheduler的用户拥有执行权限，但就是 4_3_3.command 这个文件没有执行权限，如下，这是什么原因呢？
`[root@dev03 exec]# cd /data/yananlin/soft/escheduler/exec/process/2/4/3/3

You have mail in /var/spool/mail/root
[root@dev03 3]# ll
total 8
-rw-rw-r-- 1 yananlin yananlin 195 Jun 26 20:11 4_3_3.command
-rwxr-xr-x 1 yananlin yananlin  12 Jun 26 20:11 4_3_3_node.sh
[root@dev03 3]# cd ../
[root@dev03 3]# ll
total 0
drwxrwxr-x 2 yananlin yananlin 48 Jun 26 20:11 3
[root@dev03 3]# `

**Comment by dailidong** [comment]
租户是哪个？ 调度只是代租户提交，相当于执行“sudo - 租户 sh  xxx.command”

**Comment by antti8** [comment]
这个租户我是在调度上新建的一个。是不是租户名必须是服务器上已经存在且具有sudo权限的系统用户？

**Comment by lidongdai** [comment]
租户名必须是服务器上已经存在的，不需要sudo权限


<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=lidong.dai&uid=lidong.dai%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22lidong.dai%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
lidong.dai
lidong.dai@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制

在2019年06月26日 23:29，antti8<notifications@github.com><mailto:notifications@github.com> 写道：

这个租户我是在调度上新建的一个。是不是租户名必须是服务器上已经存在且具有sudo权限的系统用户？

**Comment by antti8** [comment]
租户zuhu002，对应的用户在服务器上都存在啊

**Comment by dailidong** [comment]
你是哪个用户部署EasyScheduler的，在该部署用户下执行一下：
sudo - zuhu002 sh /data/yananlin/soft/escheduler/exec/process/2/4/3/3/4_3_3.command  

看下会报权限拒绝错误么？

**Comment by antti8** [comment]
是的，在部署用户下执行还是报错 Permission denied.
如下` sudo -u zuhu002 sh /data/yananlin/soft/escheduler/exec/process/2/4/3/3/4_3_3.command
sh: /data/yananlin/soft/escheduler/exec/process/2/4/3/3/4_3_3.command: Permission denied`

**Comment by qiaozhanwei** [comment]
你是用哪个用户部署的？

**Comment by qiaozhanwei** [comment]
进去看一下你的command，看是不是环境变量source的，没有权限

**Comment by antti8** [comment]
source 了一个这个 .escheduler_env.sh ，这个文件权限改成所有组都有执行权限，还是报权限错误呃。

**Comment by qiaozhanwei** [comment]
你微信@我吧，微信聊吧

**Comment by antti8** [comment]
微信号跟我这个id一样 antti8，麻烦加我一下？

**Comment by antti8** [comment]
已解决问题，是其中一层目录权限问题，谢谢 @dailidong 和 @qiaozhanwei  两位大佬帮忙。

**Comment by ldgithub2199** [comment]
麻烦在这里说下具体怎么解决的吧

**Comment by ldgithub2199** [comment]
@antti8 能详细说下具体原因和解决方案么，我也遇到这种问题

**Comment by ldgithub2199** [comment]
@dailidong @qiaozhanwei @antti8 能详细说下具体原因和解决方案么，我也遇到这种问题

**Comment by antti8** [comment]
我上面说了，是租户对部署应用所在的上层目录没有权限
