### ISSUE TITLE
A worker exits, zk listens for an error(一个worker退出,zk监听报错)

### ISSUE THREAD

**Issue by hujiang75277381** [analysys/EasyScheduler#525]
Environment: 1 worker, 1 api, 1 master are all on the same machine.
Problem: Every time the worker is shut down, an error is reported in the master's zk listener: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /escheduler/dead-servers/worker_xxxxxxxx
See picture for details

![企业微信截图_6f841e0b-6f1c-446e-aa6b-e8b5bf954dbd](https://user-images.githubusercontent.com/8623830/60695014-ca134900-9f12-11e9-89fd-3bf820d1f637.png)

---
环境:1个worker、1个api、1个master都在同一台机器上。
问题:每次关闭worker,在master的zk监听中都会报错：org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /escheduler/dead-servers/worker_xxxxxxxx
详情请见图片

![企业微信截图_6f841e0b-6f1c-446e-aa6b-e8b5bf954dbd](https://user-images.githubusercontent.com/8623830/60695014-ca134900-9f12-11e9-89fd-3bf820d1f637.png)

**Comment by boandai** [comment]
![image](https://user-images.githubusercontent.com/48329107/60704588-78c98080-9f37-11e9-9a59-d11cef00ac5b.png)

I don't understand why exceptions are thrown. The code has already been judged.

which version do you use?

**Comment by qiaozhanwei** [comment]
Probably because there is a concurrency issue and multiple master triggers will have problems

**Comment by qiaozhanwei** [comment]
Probably because there is a concurrency issue and multiple master triggers will have problems

**Comment by qiaozhanwei** [comment]
Probably because there is a concurrency issue and multiple master triggers will have problems

可能是因为存在并发问题，同时多个master触发就会有问题

**Comment by qiaozhanwei** [comment]
This single mster and single worker test situation：

[INFO] 2019-07-06 02:27:43.330 cn.escheduler.server.zk.ZKMasterClient:[354] - node deleted : /escheduler/workers/172.17.0.2_0000000000
[INFO] 2019-07-06 02:27:43.334 cn.escheduler.common.zk.AbstractZKClient:[288] - worker server dead , and /escheduler/workers/172.17.0.2_0000000000 added to zk dead server path success
[INFO] 2019-07-06 02:27:43.347 cn.escheduler.server.zk.ZKMasterClient:[372] - start worker failover ...
[INFO] 2019-07-06 02:27:43.351 cn.escheduler.server.zk.ZKMasterClient:[388] - worker failover end
[INFO] 2019-07-06 02:29:30.938 cn.escheduler.server.zk.ZKMasterClient:[349] - node added : /escheduler/workers/172.17.0.2_0000000001
[INFO] 2019-07-06 02:30:04.593 cn.escheduler.server.zk.ZKMasterClient:[354] - node deleted : /escheduler/workers/172.17.0.2_0000000001
[INFO] 2019-07-06 02:30:04.594 cn.escheduler.common.zk.AbstractZKClient:[288] - worker server dead , and /escheduler/workers/172.17.0.2_0000000001 added to zk dead server path success
[INFO] 2019-07-06 02:30:04.600 cn.escheduler.server.zk.ZKMasterClient:[372] - start worker failover ...
[INFO] 2019-07-06 02:30:04.601 cn.escheduler.server.zk.ZKMasterClient:[388] - worker failover end


以上是单mster和单worker的测试结果，但是没有发现兄弟说的情况，我测试了两个master的情况，由于同时两个master监听到worker掉，然后存在并发情况，判断哪里出现了并发判断，所以出现以上问题
