### ISSUE TITLE
Whether the data generated by each process node flows into the next node or is used by the next node.(各流程节点所产生的数据能否流入下一节点，或被下一节点所用。)

### ISSUE THREAD

**Issue by mnloveyx** [analysys/EasyScheduler#531]
Whether the data generated by each process node flows into the next node or is used by the next node.

---
各流程节点所产生的数据能否流入下一节点，或被下一节点所用。

**Comment by dailidong** [comment]
very good！ thx
does this issue like #116 ?

**Comment by boandai** [comment]
becase the similar issue #116 ，close this issue！
