### ISSUE TITLE
EasyScheduler-JDK兼容问题

### ISSUE THREAD

**Issue by zhuwep** [analysys/EasyScheduler#566]
后端使用Oracle官方JDK1.8 部署启动（API）报错，换成OPENJDK1.8可以正常启动

异常信息：
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:94)
        at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:100)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:422)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:892)
...

**Comment by zhuwep** [comment]
建议在部署文档里说明并提示使用 OPENJDK1.8

**Comment by qiaozhanwei** [comment]
We use Oracle official jdk1.8 internally, and open jdk 1.8 in docker. At present, we have not encountered such a problem. We will locate it according to your environment.

我们内部使用的是Oracle官方jdk1.8，docker中使用的是open jdk 1.8，目前没有遇到这样问题，根据你的环境我们定位一下

**Comment by zhuwep** [comment]
环境信息：

Linux idc.corp.com 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by qiaozhanwei** [comment]
Which service starts reporting this error?

哪个服务启动报这个错误？

**Comment by qiaozhanwei** [comment]
[root@3d722ff6f095 logs]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@3d722ff6f095 logs]# java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
[root@3d722ff6f095 logs]# jps
215 ApiApplicationServer
551 Jps
[root@3d722ff6f095 logs]#

**Comment by zhuwep** [comment]
神奇，但是看报错信息是JDK相关， 还是感谢回复。
