### ISSUE TITLE
When offline process, offline timing is error.

### ISSUE THREAD

**Issue by datuzi** [analysys/EasyScheduler#567]
When offline process, it should first offline process according to process ID, and then according to the corresponding timing ID offline timing.

In fact, the offline timing is based on the process ID, as follows:
**ProcessDefinitionService: delete Schedule (project. getId (), id);**

It should be amended to read:
**ProcessDefinitionService: delete Schedule (project. getId (), schedule. getId ());**

**Comment by qiaozhanwei** [comment]
OK，we will fix 1.1.0 and we welcome the contribution code.

**Comment by boandai** [comment]
> When offline process, it should first offline process according to process ID, and then according to the corresponding timing ID offline timing.
> 
> In fact, the offline timing is based on the process ID, as follows:
> **ProcessDefinitionService: delete Schedule (project. getId (), id);**
> 
> It should be amended to read:
> **ProcessDefinitionService: delete Schedule (project. getId (), schedule. getId ());**

very very good job!   thanks a lot !   Would you like to contribute  code to fix this issue?

**Comment by boandai** [comment]
thank you for pr！
very great！
