### ISSUE TITLE
定时任务无法真正停止

### ISSUE THREAD

**Issue by wuchunfu** [analysys/EasyScheduler#569]
我今天遇到一个比较奇怪的问题，当我把定时任务下线后好像定时任务没有真正停止，过一会儿就会自己运行一批任务，我把定时任务删除后也不起作用，过一会儿还是自己运行一批任务。

**Comment by qiaozhanwei** [comment]
We have located the problem and will fix it in version 1.1.0.

我们已经定位到了问题的所在，会在1.1.0版本中解决
