### ISSUE TITLE
Cannot delete queue problem（不能删除队列问题）

### ISSUE THREAD

**Issue by wuchunfu** [analysys/EasyScheduler#587]
When I create an error or don't want this queue, I want to be able to delete the queue. Not only delete the background data on the page but also delete it. I think `Queue Management` is only incomplete.

current version:
`1.0.4 release`

The desired effect:
Ability to delete queues

---
当我创建错误或不想要这个队列的时候我希望能够删除队列，不单单是在页面删除后台数据也要删除，我认为 `队列管理` 只有编辑队列这个功能是不完整的。

当前版本：
`1.0.4 release`

希望达到的效果：
能够删除队列

**Comment by boandai** [comment]
queue manage is used for yarn queue
if delete queue, the yarn queue  delete or not ?

**Comment by wuchunfu** [comment]
如果我添加一个队列，但是 `yarn` 上面没有这个队列，`Easy Scheduler` 会创建队列或会校验 `yarn` 上面是否有这个队列吗？

**Comment by boandai** [comment]
we will not create queue on yarn for now,  also will not check this queue on yarn

**Comment by wuchunfu** [comment]
多谢，我大概了解了。
