### ISSUE TITLE
前端安装包缺少文件

### ISSUE THREAD

**Issue by jyc1996** [analysys/EasyScheduler#599]
nginx打开首页后，报错：/escheduler/users/get-user-info Not Found ，查看dist目录中相应路径，并未发现相关文件。

**Comment by jyc1996** [comment]
![image](https://user-images.githubusercontent.com/41460919/61437083-d960b080-a96e-11e9-87f1-297ba3aca5e3.png)

**Comment by jyc1996** [comment]
![image](https://user-images.githubusercontent.com/41460919/61437218-1b89f200-a96f-11e9-8e48-3fac47eb2389.png)

**Comment by jyc1996** [comment]
![image](https://user-images.githubusercontent.com/41460919/61437338-69065f00-a96f-11e9-8df9-a1a9b6db3760.png)

**Comment by qiaozhanwei** [comment]
This should be connected to the api server service.

这应该是连接不上api  server服务

**Comment by jyc1996** [comment]
![image](https://user-images.githubusercontent.com/41460919/61675536-543d1900-ad2b-11e9-9540-928179bc2d98.png)
我测试了一下api sever服务 确实如此
安装步骤均是按照文档一步一步操作的 请问这种问题如何解决？

**Comment by boandai** [comment]
first, plese  `telnet anp | grep 12345` to confirm the service of api server has been already started?
 
second, if there is some exception in api server runtime log ?

**Comment by jyc1996** [comment]
Thank you, everyone, I already know where the problem is
![image](https://user-images.githubusercontent.com/41460919/61678323-1b09a680-ad35-11e9-9707-3ba68bbc70d6.png)
The configuration of this directory has been modified by myself. I change it back to the default value then the problem has gone.

**Comment by jyc1996** [comment]
Please complete the installation documentation， tell us about the meaning or role of the parameters in ”install.sh“
