### ISSUE TITLE
提几个问题，请帮忙解答

### ISSUE THREAD

**Issue by bg1011** [analysys/EasyScheduler#616]
对于通过Yarn提交的任务，比如MR（Hive），Flink，SparkOnYarn（Cluster，Client）对如何操作，通过Shell吗？
对于长周期任务，比如Spark|Flink|Kafka Stream流任务是否提供支持?
在线的流程图是否支持导出，比如以xml方式或者类似conf方式，同时支持导入流程
另外，工作流和任务实例，是否能按照名称聚合，并提供时序统计曲线~
另外，请问上述是否有计划？

**Comment by boandai** [comment]
1、对于通过Yarn提交的任务，比如MR（Hive），Flink，SparkOnYarn（Cluster，Client）对如何操作，通过Shell吗？
---
MR、Spark是支持的，Flink暂不支持

2、对于长周期任务，比如Spark|Flink|Kafka Stream流任务是否提供支持?
---
Spark是支持的，Flink、kafka stream暂不支持

3、在线的流程图是否支持导出，比如以xml方式或者类似conf方式，同时支持导入流程
---
这个已经有伙伴提出了，欢迎在对应issue下回复+1之类的，方便研发伙伴根据关注度进行研发

4、另外，工作流和任务实例，是否能按照名称聚合，并提供时序统计曲线~
---
请单提issue，咱们是根据issue的关注程度进行研发计划的

最后建议先看完文档呐！

**Comment by boandai** [comment]
如果关注某项功能，请单提issue吧
