### ISSUE TITLE
Front-end interface deployment k8s, background deployment big data cluster session error（前端界面部署k8s，后台部署大数据集群session错误）

### ISSUE THREAD

**Issue by crazycarry** [analysys/EasyScheduler#622]
There is an interface session switch on the front-end deployment k8s, which is estimated based on the ip-seence. The next request routing address is different, resulting in a return login interface.

---
前端部署k8s 上存在界面session回切换，估计基于ip的seesion。下次请求路由地址不一样导致返回登录界面

**Comment by boandai** [comment]
very good!
version 1.1.0 release will fix this problem!  we will remove  the rules through ip！
