### ISSUE TITLE
Different sql node task logs in parallel in the same workflow will be mixed（同一工作流中并行的不同sql节点任务日志会混合）

### ISSUE THREAD

**Issue by chenyuan9028** [analysys/EasyScheduler#627]
In the same workflow, the sql node task executed in parallel, the execution log of task B will appear in the log of task A, which may eventually cause the variable replacement of a task to fail.
![image](https://user-images.githubusercontent.com/30412237/61792807-2a314700-ae50-11e9-995a-9b31cb3ffd2c.png)
![image](https://user-images.githubusercontent.com/30412237/61792837-387f6300-ae50-11e9-9b41-ea4cc5a8d46e.png)
As shown above, status_fav_num and status_retweet_num are two separate tasks, but the execution log of the status_retweet_num task appears in the status_fav_num task log.
For detailed log of the above 4 tasks, you can contact me (WeChat group: EasyScheduler China User Group 1 Chen Yuan)

---
在同一工作流中，并行执行的sql节点任务，任务A的日志里会出现任务B的执行日志，最终可能导致某个任务的变量替换失败。
![image](https://user-images.githubusercontent.com/30412237/61792807-2a314700-ae50-11e9-995a-9b31cb3ffd2c.png)
![image](https://user-images.githubusercontent.com/30412237/61792837-387f6300-ae50-11e9-9b41-ea4cc5a8d46e.png)
如上图，status_fav_num和status_retweet_num是两个独立的任务，但是在status_fav_num任务日志中出现了status_retweet_num任务的执行日志。
如需要以上4个任务的详细日志，可以联系我（微信群：EasyScheduler China User Group 1 陈源)

**Comment by qiaozhanwei** [comment]
https://github.com/analysys/EasyScheduler/pull/651 pr solved.

**Comment by boandai** [comment]
good job！
