### ISSUE TITLE
CONTRIBUTING.md need set to EN

### ISSUE THREAD

**Issue by wu-sheng** [analysys/EasyScheduler#637]
The link at here, https://github.com/analysys/EasyScheduler#how-to-contribute-code, is pointing to Chinese document. Need to fix.

**Comment by boandai** [comment]
yes，we will translate it to english！thx！

**Comment by boandai** [comment]
done！

**Comment by wu-sheng** [comment]
link is still not working.

**Comment by boandai** [comment]
oh, i only translate the issue: [How to contribute code?](https://github.com/analysys/EasyScheduler/issues/310)

but not update the README.md,  most of the links in README doc are still in Chinese.  We are in the process of translation！

**Comment by wu-sheng** [comment]
Just use relative path, which is friendly to version and language separated.

**Comment by wu-sheng** [comment]
Could someone add me as a member of org or project team?

**Comment by boandai** [comment]
> Just use relative path, which is friendly to version and language separated.
good idea！

Invitation has been sent，please check！
