### ISSUE TITLE
[Feature]It is recommended to upload the resources of hdfs in the structure of the directory tree.（建议上传hdfs的资源以目录树的结构存放）

### ISSUE THREAD

**Issue by dskys** [analysys/EasyScheduler#642]
It is recommended that the resources for uploading hdfs be stored in the structure of the directory tree.

---
[Feature]建议上传hdfs的资源以目录树的结构存放，现在资源多了就不好管理了

**Comment by dailidong** [comment]
Duplicate of  #121 ， this issue will be closed！
