### ISSUE TITLE
The interface link in the official documentation is wrong（官方说明文档中的接口链接是错误的）

### ISSUE THREAD

**Issue by KevinOfChina** [analysys/EasyScheduler#644]
The interface link in the official documentation is wrong. Clicking is an error page for nginx
http://52.82.13.76:8888/easyscheduler/doc.html?language=zh_CN&lang=cn

---
官方说明文档中的接口链接是错误的.点开是个nginx的错误页面
http://52.82.13.76:8888/easyscheduler/doc.html?language=zh_CN&lang=cn

**Comment by boandai** [comment]
thx！
please use this address：
http://52.82.13.76:8888/escheduler/doc.html?language=zh_CN&lang=cn

**Comment by lenboo** [comment]
we have already fixed it.
