### ISSUE TITLE
[Discussion] Why doesn't ProcessScheduleJob add @DisallowConcurrentExecution（[Discussion] ProcessScheduleJob为什么不加上@DisallowConcurrentExecution）

### ISSUE THREAD

**Issue by sad-apple** [analysys/EasyScheduler#646]
Excuse me, why does ProcessScheduleJob not add the @DisallowConcurrentExecution annotation? The current scheduled execution should be executed concurrently. Is it more reasonable to wait until the last execution? There are still other reasons to implement better, and ask you

---
请问下ProcessScheduleJob为什么不加上@DisallowConcurrentExecution注解，现在的定时执行应该都是并发执行吧，等到上个执行完再执行不是更合理？还是有其他的理由并发执行更好，，，请教一下各位

**Comment by boandai** [comment]
sometimes，multiple instances will be executed concurrently

**Comment by sad-apple** [comment]
how to execute instances asynchronous?
