### ISSUE TITLE
[BUG] Creating a hive data source without a principal will cause the connection to fail.（建立hive数据源principal未开启的时候会导致连接失败）

### ISSUE THREAD

**Issue by 307526982** [analysys/EasyScheduler#650]
In version 1.1.0, when the hive data source is created, the principal is not enabled, the principal field returns null, and is spliced into the string of jdbcUrl with principal=null, which will eventually cause the connection to fail. If this sentence is removed, it will be OK.

Modify the HiveDataSource rewrite method getJdbcUrl field to judge.

---
1.1.0版本中 ，建立hive数据源的时候principal未开启，principal字段返回的null，并被拼接到jdbcUrl的字符串当中principal=null，最终会导致连接失败，如果把这句去掉就OK了。

修改方式HiveDataSource的重写方法getJdbcUrl字段进行判断即可。

**Comment by boandai** [comment]
good job！ thx！
please add title for this issue

**Comment by qiaozhanwei** [comment]
https://github.com/analysys/EasyScheduler/pull/651 pr solved.

**Comment by boandai** [comment]
@307526982 ,please add title!
