### ISSUE TITLE
The 1.1.0 version of the backend deployment script removes zookeeper, the python script does not support python3, python2 has been resolved!（1.1.0版本后端部署脚本删除zookeeper,python脚本不支持python3，python2已解决！）

### ISSUE THREAD

**Issue by zhanghaicheng1** [analysys/EasyScheduler#660]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by boandai** [comment]
very good, thank you !

**Comment by qiaozhanwei** [comment]
(base) root@56b9cc9bdcda:/# python -V
Python 3.7.3
(base) root@56b9cc9bdcda:/# python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import sys
>>> from kazoo.client import KazooClient
   self.zk.delete("/test", recursive=True)
        print('deleted success')
    def __del__(self):
        self.zk.stop()>>> 
>>> class ZkClient:
...     def __init__(self):
...         self.zk = KazooClient(hosts="192.168.220.188:2181,192.168.220.189:2181,192.168.220.190:2181")
...         self.zk.start()
...     def del_node(self):
...         self.zk.delete("/test", recursive=True)
...         print('deleted success')
...     def __del__(self):
...         self.zk.stop()
... 
>>> zkclient = ZkClient()
>>>     zkclient.del_node()
  File "<stdin>", line 1
    zkclient.del_node()
    ^
IndentationError: unexpected indent
>>>     time.sleep(2)
  File "<stdin>", line 1
    time.sleep(2)
    ^
IndentationError: unexpected indent
>>> zkclient = ZkClient()
>>> zkclient.del_node()
deleted success
>>> time.sleep(2)



This may not be a bug, it may be improper operation.
