### ISSUE TITLE
How to change the boot port of the master?（如何改变master的启动端口？）

### ISSUE THREAD

**Issue by chekore** [analysys/EasyScheduler#665]
How to change the boot port of the master?
![image](https://user-images.githubusercontent.com/8263441/62352160-0f3e9100-b53a-11e9-95ba-3ae3dde49c72.png)

---
如何改变master的启动端口？
![image](https://user-images.githubusercontent.com/8263441/62352160-0f3e9100-b53a-11e9-95ba-3ae3dde49c72.png)

**Comment by qiaozhanwei** [comment]
modify application_master.properties
for example：
# server port
server.port=12345

**Comment by qiaozhanwei** [comment]
modify application_master.properties
for example：

server.port=12345
