### ISSUE TITLE
The upload resource file is configured as hdfs, and the upload of the JAR package file is unsuccessful.（上传资源文件配置为hdfs，上传JAR包文件不成功）

### ISSUE THREAD

**Issue by chekore** [analysys/EasyScheduler#671]
After the resource file storage type is configured as HDFS, the uploaded file will report the following error:
![image](https://user-images.githubusercontent.com/8263441/62444549-6178ef80-b790-11e9-8440-073abe341086.png)
The file name and type of the uploaded file are as follows:
![image](https://user-images.githubusercontent.com/8263441/62444597-853c3580-b790-11e9-89f5-06ead1498066.png)

---
把资源文件存放类型配置为HDFS后，上传文件会报如下错误：
![image](https://user-images.githubusercontent.com/8263441/62444549-6178ef80-b790-11e9-8440-073abe341086.png)
上传的文件名称和类型如下：
![image](https://user-images.githubusercontent.com/8263441/62444597-853c3580-b790-11e9-89f5-06ead1498066.png)

**Comment by chekore** [comment]
api server日志没有错误信息。

**Comment by William-GuoWei** [comment]
502: Bad Gateway

Turn off open SS or other agents

---
代理是开着的么，关闭代理

**Comment by chekore** [comment]
> 502: Bad Gateway
> 
> Turn off open SS or other agents
> 
> 代理是开着的么，关闭代理

和代理无关，经过我的测试，源文件能够上传，但是当程序编译后打成JAR后上传会出现如上问题，如果把这个jar包再打包成zip包（或者其他类型压缩包）都是可以上传成功的。如下图（这应该是一个bug）：
![image](https://user-images.githubusercontent.com/8263441/62452076-0ea83380-b7a2-11e9-82a3-27b5d8f21955.png)

**Comment by William-GuoWei** [comment]
What is the size of the file you uploaded?

**Comment by chekore** [comment]
> What is the size of the jar file you uploaded?
> if the file is too big, please
> edit file
> 
> vi /etc/nginx/nginx.conf , add
> 
> `client_max_body_size 1024m`

The file size:
![image](https://user-images.githubusercontent.com/8263441/62453818-b6733080-b7a5-11e9-83f5-10ca5ab70ce5.png)

**Comment by William-GuoWei** [comment]
add `client_max_body_size 1024m` , then restart nginx, and try?  
I'm sorry , we don't know the cause for now, we upload jar normally, 

![image](https://user-images.githubusercontent.com/25520639/62454160-68126180-b7a6-11e9-95c0-ce82a93121fb.png)

**Comment by chekore** [comment]
> add `client_max_body_size 1024m` , then restart nginx, and try?
> I'm sorry , we don't know the cause for now, we upload jar normally,
> 
> ![image](https://user-images.githubusercontent.com/25520639/62454160-68126180-b7a6-11e9-95c0-ce82a93121fb.png)

It's my fault. The real reason is the "ladder".

**Comment by wusober** [comment]
> > add `client_max_body_size 1024m` , then restart nginx, and try?
> > I'm sorry , we don't know the cause for now, we upload jar normally,
> > ![image](https://user-images.githubusercontent.com/25520639/62454160-68126180-b7a6-11e9-95c0-ce82a93121fb.png)
> 
> It's my fault. The real reason is the "ladder".

hello, i met same situation with u, can u please tell me the reason and how to solve it?
