### ISSUE TITLE
How to specify a user when a workflow defines MR（工作流定义MR时如何指定用户）

### ISSUE THREAD

**Issue by chekore** [analysys/EasyScheduler#673]
How to specify the user when the workflow defines the MR task. The default is to use the tenant code, as shown in the following log:
![image](https://user-images.githubusercontent.com/8263441/62515147-001a5480-b854-11e9-8771-3e590653dda6.png)
![image](https://user-images.githubusercontent.com/8263441/62515166-11fbf780-b854-11e9-86ca-1147f24cd251.png)

---
工作流定义MR任务时如何指定用户，默认使用的是租户编码，如下图日志：
![image](https://user-images.githubusercontent.com/8263441/62515147-001a5480-b854-11e9-8771-3e590653dda6.png)
![image](https://user-images.githubusercontent.com/8263441/62515166-11fbf780-b854-11e9-86ca-1147f24cd251.png)

**Comment by qiaozhanwei** [comment]
The deployment user needs to have the /escheduler root privilege. If the hdfsRootUser privilege is set in install.sh, then hdfsRootUser needs /escheduler root privilege

部署用户需要有/escheduler根权限，如果在 install.sh 中设置了hdfsRootUser 权限，则需要 hdfsRootUser 有/escheduler根权限

**Comment by chekore** [comment]
> The deployment user needs to have the /escheduler root privilege. If the hdfsRootUser privilege is set in install.sh, then hdfsRootUser needs /escheduler root privilege
> 
> 部署用户需要有/escheduler根权限，如果在 install.sh 中设置了hdfsRootUser 权限，则需要 hdfsRootUser 有/escheduler根权限

不，我的MR程序需要读写HDFS上的其他目录（非/escheduler目录）

**Comment by chekore** [comment]
Temporary fix, specifying associated users for mapreduce programs in weak authentication mode，`export HADOOP_USER_NAME`
