### ISSUE TITLE
How to make the Edit button of the properties file clickable on the web page

### ISSUE THREAD

**Issue by chekore** [analysys/EasyScheduler#674]
How to make the edit button of the properties file clickable on the web page, as shown below:

![image](https://user-images.githubusercontent.com/8263441/62605003-cb79cc00-b92b-11e9-907e-14e0151e4300.png)

I added the properties type to the common configuration file and it did not work.

![image](https://user-images.githubusercontent.com/8263441/62605117-07ad2c80-b92c-11e9-9fc3-d0fafb7e8d2f.png)

**Comment by boandai** [comment]
why it does't work?  please show error, thx!

**Comment by chekore** [comment]
> why it does't work? please show error, thx!

no errors, as shown below:
![image](https://user-images.githubusercontent.com/8263441/62611579-72fcfb80-b938-11e9-8b5c-02c20a3034f4.png)

**Comment by chekore** [comment]
> why it does't work? please show error, thx!

no errors, as shown below:
![image](https://user-images.githubusercontent.com/8263441/62611693-a9d31180-b938-11e9-9e8d-43ec4b06b462.png)

**Comment by chekore** [comment]
> why it does't work? please show error, thx!

After modifying the configuration file, I need to recompile the back-end service?

**Comment by chekore** [comment]
> > why it does't work? please show error, thx!
> 
> After modifying the configuration file, I need to recompile the back-end service?

found it

![image](https://user-images.githubusercontent.com/8263441/62668493-ac784a00-b9be-11e9-9cf3-e67d53e2781e.png)

**Comment by chekore** [comment]
> > > why it does't work? please show error, thx!
> > 
> > 
> > After modifying the configuration file, I need to recompile the back-end service?
> 
> found it
> 
> ![image](https://user-images.githubusercontent.com/8263441/62668493-ac784a00-b9be-11e9-9cf3-e67d53e2781e.png)

and here

![image](https://user-images.githubusercontent.com/8263441/62668960-586e6500-b9c0-11e9-9367-c774a6209ec3.png)

**Comment by chekore** [comment]
> > > > why it does't work? please show error, thx!
> > > 
> > > 
> > > After modifying the configuration file, I need to recompile the back-end service?
> > 
> > 
> > found it
> > ![image](https://user-images.githubusercontent.com/8263441/62668493-ac784a00-b9be-11e9-9cf3-e67d53e2781e.png)
> 
> and here
> 
> ![image](https://user-images.githubusercontent.com/8263441/62668960-586e6500-b9c0-11e9-9367-c774a6209ec3.png)

It's work.

![image](https://user-images.githubusercontent.com/8263441/62672243-92ddff00-b9cc-11e9-8af0-5a2a51716abb.png)

![image](https://user-images.githubusercontent.com/8263441/62672283-ba34cc00-b9cc-11e9-90df-45aebd52a670.png)
