### ISSUE TITLE
[Feature]Modify the port number of workerSSH（修改workerSSH的端口号）

### ISSUE THREAD

**Issue by zongyaoou** [analysys/EasyScheduler#675]
Is it possible to customize the commands sent to the worker?
For some special reasons, SSH default 20 port is disabled, so I want to use SSH to specify the port to drive the worker work;

---
请问有可能定制发送给worker的命令吗 ?  
由于某些特别的原因 , SSH默认20端口被禁用了 , 所以想通过SSH指定端口去驱动worker工作 ;

**Comment by boandai** [comment]
Ssh is only required when deploying this system

you can change ` install.sh`, this file has some related port !
