### ISSUE TITLE
[Ask a question]master port is occupied（master端口被占用)

### ISSUE THREAD

**Issue by LoveEvenWong** [analysys/EasyScheduler#684]
Hello, I encountered a problem during the installation process, help me answer
  The master service is enabled on port 8080, but I have other services that take up this port. I have to ask how to modify the port. I don't see any changes. Many thanks

---
您好，我在安装过程中遇到一个问题麻烦帮忙解答一下
 master服务在8080端口启用，但是我有别的服务占用了这个端口，麻烦问一下如何修改端口，没有看到可以修改的地方。万分感谢

**Comment by boandai** [comment]
add port in application_master.properties

`
server.port=xxxx
`
![image](https://user-images.githubusercontent.com/48329107/62751659-1106d800-ba97-11e9-858c-e18f295f055d.png)
