### ISSUE TITLE
[BUG] there is no error log, and the result is also generated normally, but the display status is failure, sometimes it will be displayed after retrying.（任务日志无报错，结果也正常生成，但显示状态为失败，有时重试后会显示成功）

### ISSUE THREAD

**Issue by chenyuan9028** [analysys/EasyScheduler#685]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
任务日志无报错，结果也正常生成，但显示状态为失败，有时重试后会显示成功

![image](https://user-images.githubusercontent.com/30412237/62749571-81a9f680-ba8f-11e9-90af-c9dabf9a2064.png)

version：1.0.3

**Comment by qiaozhanwei** [comment]
1, if it is a YARN task, our judgment is based on the SHELL script exit, first determine whether the return code of the SHELL script is successful, if successful, determine whether the YARN task is successful, then divided into (success, failure, KILL). However, there is another state that is Running. If it is Running, the judgment of the version is a direct failure. Improved this problem in 1.0.4

2, look at a Task log and Worker log, you should be able to see the problem
3, or in the test environment DEBUG


1，如果是YARN任务，我们的判断依据是SHELL脚本退出之后，首先判断SHELL脚本的返回码是否是成功，如果成功，则判断YARN任务是否成功，这时分为（成功，失败，KILL）。不过还有一种状态就是Running，如果是Running的化，对于版本的判断是直接失败。在1.0.4中改进了这个问题

2，自己看一个Task 日志和Worker 日志，应该能看出问题
3，或者在测试环境DEBUG一下

**Comment by dailidong** [comment]
has the problem been done？ temporarily close this issue！ if not done, please reopen it!
