### ISSUE TITLE
[BUG] TaskQueueZkImpl.poll() throw NullPointerException

### ISSUE THREAD

**Issue by w771920097** [analysys/EasyScheduler#700]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
TaskQueueZkImpl.poll()
task queue poll error, task detail :2_1_2_1_-1 , please check!
add task to tasks queue exception
java.lang.NullPointerException: null.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 部署易调度1.0.5版本
2. 创建任务
3. 查看worker日志
4. TaskQueueZkImpl的poll方法报空指针异常

**Expected behavior**

**Screenshots**

- 日志

![image](https://user-images.githubusercontent.com/30776503/62940554-6da32380-be06-11e9-9345-89ae414c879d.png)

- 代码

![image](https://user-images.githubusercontent.com/30776503/62940608-87446b00-be06-11e9-8891-11311cf7e9e4.png)

**Which version of Easy Scheduler:**
 -[1.0.5]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
version 1.0.5 
from the exception log，I see the source code
![image](https://user-images.githubusercontent.com/15833811/63069958-de078d00-bf4b-11e9-934e-8e129e1dfd0a.png)

in version 1.0.5 ，
There should be no -1 after task detail:2_1_2_1 ，`with -1` should be version 1.1.0 for now!  
when split by ‘_’ , then the last one is the machine groups corresponding to the task.

---
 在1.0.5版本中，task detail：2_1_2_1 后面不会带-1, 1.1.0才有机器分组的功能，最后一位是任务对应的 机器分组
