### ISSUE TITLE
[Suggestion] Project rename

### ISSUE THREAD

**Issue by cabbage89** [analysys/EasyScheduler#701]
**Da Yu**, (Chinese: “Yu the Great”)Wade-Giles romanization Ta Yü, in Chinese mythology, the Tamer of the Flood, a saviour-hero and reputed founder of China’s oldest dynasty, the Xia. One legend among many recounts Da Yu’s extraordinary birth: a man called Gun was given charge of controlling a great deluge. To dam the water, he stole from heaven what seems to have been a piece of magic soil. Angered by the theft, the Lord on High (Shangdi) issued an order for his execution. After three years Gun’s miraculously preserved body was slit open and a son brought forth. This was Da Yu who, after years of strenuous labour, provided outlets to the sea through dredging, with the aid of dragons, thus making the world suitable for human habitation.

Usually a river has many source branches, which eventually flow into a main river, and the data flow is similar to a river. The purpose of this project is data flow management. Dayu can dredge these rivers, so I think it would be very much to name the project **dayu**. Meaningful and visual

**Comment by dailidong** [comment]
https://issues.apache.org/jira/browse/PODLINGNAMESEARCH-151

has already exists!

**Comment by dailidong** [comment]
some other project name maybe ?

**Comment by William-GuoWei** [comment]
How about "dophin scheduler"? Our logo also has a dolphin, haha

**Comment by cabbage89** [comment]
**DataDAG**
https://www.trademarkia.com/trademarks-search.aspx?tn=datadag
https://github.com/search?q=datadag&type=Repositories
https://www.openhub.net/p?query=datadag&sort=relevance
https://sourceforge.net/directory/os:mac/freshness:recently-updated/?q=datadag

**Comment by William-GuoWei** [comment]
I just make a vote for a new name on Tencent Questionnaire as following link https://wj.qq.com/s2/4315715/0655/
Please vote for your favorite name

**Comment by coding-now** [comment]
DTES/dtes
Distributed-Task-Easy-Scheduler
DT时代的 EasyScheduler

**Comment by William-GuoWei** [comment]
Till now the result is:
https://wj.qq.com/stat_chart_share.html?id=4315715&share_id=58r5gmie9
![image](https://user-images.githubusercontent.com/25520639/63277648-481b8b80-c2d8-11e9-8cb9-f5bc72fb8c36.png)
![image](https://user-images.githubusercontent.com/25520639/63277665-4eaa0300-c2d8-11e9-8073-d93ce906c1f8.png)

More than half of community people vote for Dolphin Scheduler

**Comment by dailidong** [comment]
Regarding the project name potential conflict risk, through a public community vote, we are going to use `DolphinScheduler` as the new project name.

**Comment by cabbage89** [comment]
Oxherd
1. Just as apache has zookeeper, **oxherd** means cattle keeper
2. Since ancient times, cattle have been farming for people, symbolizing workers. The role of this project is also to manage these workers.

**Comment by wukele** [comment]
1

**Comment by dailidong** [comment]
Regarding the project name potential conflict risk, through a public community vote, we are going to use DolphinScheduler as the new project name.

Thank you to everyone who named the project, voted for it, and followed the progress of the project！

so DolphinScheduler will be the new project name！ thanks again！
