### ISSUE TITLE
backend deploy script not support python3, but support python2(后端部署脚本不支持python3，python2支持！！！)

### ISSUE THREAD

**Issue by zhanghaicheng1** [analysys/EasyScheduler#708]
The Python environment of the three main servers in my cluster is 3. One of the slave Python environment is 2. But the primary node is deployed to the fourth step, which indicates that the zookeeper node has been stuck since the deletion of the zookeeper node is successful. But I succeeded in deploying the back-end script with my server with Python 2 environment, and the last answer was useless.

---
我的集群三台服务器主节点python环境是3，其中一台从节点python环境是2，但是主节点一件部署到第四步骤卡住，提示删除zookeeper节点成功之后就一直卡住。但是我用我带python2环境的服务器部署后端脚本就成功了，上次的解答没有用。

**Comment by dailidong** [comment]
Which step is stuck?

**Comment by zhanghaicheng1** [comment]
Thank you for your reply，
It was the fourth step that got stuck.

> 在 2019年8月19日，下午3:02，dailidong <notifications@github.com> 写道：
> 
> Which step is stuck?

**Comment by dailidong** [comment]
![image](https://user-images.githubusercontent.com/15833811/63245884-d3266280-c293-11e9-9de4-a3e1c8142a65.png)

does `SSH Secret-Free Configuration` right?

**Comment by zhanghaicheng1** [comment]
Thank you for your reply,
The SSH of the master node and other machines (slave nodes) has been connected.

**Comment by dailidong** [comment]
so the lastest log is ? 
![image](https://user-images.githubusercontent.com/15833811/63249458-1553a200-c29c-11e9-95fa-7242cf29294a.png)

**Comment by LiemLin** [comment]
I also encountered this problem and found that kazoo self.zk.stop() in del_zk_node.py did not exit

**Comment by qiaozhanwei** [comment]
1,[zk: localhost:2181(CONNECTED) 6] ls /test
[]

2,python script
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import time
>>> import sys
>>> from kazoo.client import KazooClient
   self.zk.delete("/test", recursive=True)
        print('deleted success')
    def __del__(self):
        self.zk.stop()>>> 
>>> class ZkClient:
...     def __init__(self):
...         self.zk = KazooClient(hosts="192.168.220.188:2181,192.168.220.189:2181,192.168.220.190:2181")
...         self.zk.start()
...     def del_node(self):
...         self.zk.delete("/test", recursive=True)
...         print('deleted success')
...     def __del__(self):
...         self.zk.stop()
... 
>>> zkclient = ZkClient()
>>> zkclient.del_node()
deleted success
>>> time.sleep(2)
>>>

3,[zk: localhost:2181(CONNECTED) 7] ls /test
Node does not exist: /test

Python3 is no problem, you can call it separately to see if the environment variable is not configured correctly. Some brothers have encountered this problem before.

**Comment by zhanghaicheng1** [comment]
已解决

**Comment by ldgithub2199** [comment]
![image](https://user-images.githubusercontent.com/65696427/83101857-dc2b4680-a0e5-11ea-9364-ba2ea2f9910d.png)
没看懂，我也遇到同样问题
