### ISSUE TITLE
Zookeeper Connection Number Not Released(Zookeeper 连接数未释放)

### ISSUE THREAD

**Issue by wuchunfu** [analysys/EasyScheduler#716]
I found a problem. When I clicked on `Master` or `Worker` on the left side of `Monitoring Center` , and then clicked on `Zookeeper` to see `Connection Number` , I found that the number of `Master` or `Worker` would increase by one for every click and then look at `Zookeeper` , because `Zookeepr` has default `Connection Number` When the number of connections exceeds `Zookeeper` , the `Master` and `Worker` service values cannot be registered properly to `Zookeeper` , which results in the operation being unable to execute normally.

**Current version in use:**

`1.1.0-release`

**Expected results:**

Hope to fix this problem, and then click on `Master'or `Worker` , the `Zookeeper` `connection number` will not increase, and the service can be registered normally.

---

我发现一个问题, 当我在 `监控中心` 点击一次左侧的 `Master` 或 `Worker` 然后再点击 `Zookeeper` 查看 `连接数` 的时候, 发现每点击一次 `Master` 或 `Worker` 然后查看 `Zookeeper` 的 `连接数` 都会增加一, 由于 `Zookeeper` 是有默认的 `连接数` 的, 当超过 `Zookeeper` 的 `连接数` 的时候, `Master` 和 `Worker` 服务值无法正常注册到 `Zookeeper` 然后导致作业无法正常执行.

**当前使用版本:**

`1.1.0-release`

**期望结果:**

希望能修复这个问题，然后再点击 `Master` 或 `Worker` 的时候 `Zookeeper` 的 `连接数` 不会递增, 服务能够正常注册

**Comment by dailidong** [comment]
@lenboo  please check this issue！

**Comment by lenboo** [comment]
we have fix it in version of 1.1.0_release. please check that.

**Comment by dailidong** [comment]
@wuchunfu , recheck ?

**Comment by wuchunfu** [comment]
Well, maybe I've got the wrong version. We're currently using `1.1.0-preview`.
