### ISSUE TITLE
[BUG]开启kerberos认证之后，隔一天之后tgt失效

### ISSUE THREAD

**Issue by phoenixhadoop** [analysys/EasyScheduler#742]
在开启了kerberos之后，上传文件到hdfs正常。

但是过了一天之后，tgt失效了，再次上传文件，后端api-server的日志中报kerberos认证失败。无效的tgt。

**Comment by phoenixhadoop** [comment]
重启escheduler服务之后，上传文件到hdfs正常，kerberos认证正常。

**Comment by qiaozhanwei** [comment]
OK，I will check it out.

**Comment by qiaozhanwei** [comment]
Beacuse HadoopUtils is singleton 
so need modify below if kerberos is startup ： 

public static HadoopUtils getInstance(){
        // if kerberos startup，need new instance
        if (CommonUtils.getKerberosStartupState())  {
            return new HadoopUtils();
        }
        return instance;
    }

**Comment by shiliquan** [comment]
Hello! I also encountered this problem, file upload hdfs to read the file on the hdfs normal, do the timing task, but after a day to execute the failure, reported tgt failure, this case I restart the next work process to return to normal, but if there is no scheduled task to carry out, I would be OK to carry out a few days later, what is the reason? SOLVER!
