### ISSUE TITLE
如果想要自定义worker,EsScheduler只做任务流调度服务，当前支持？

### ISSUE THREAD

**Issue by yangjiajun2014** [analysys/EasyScheduler#8]

**Comment by lidongdai** [comment]
WorkServer和MasterServer是通过queue进行通信的，二者之间除了故障转移外没有太多联系， 因此自定义worker理论是支持的。不过还是建议阅读完WorkerServer的实现，及MasterServer实现，对他们有了解后再做修改！

ps：还是想知道基于什么考虑想自定义Worker呢？

**Comment by yangjiajun2014** [comment]
感谢，正在阅读。

有以下几个考虑：
1.我们已经有很多long-running类型的任务，这些任务也基本上是插件化的，之前不支持编排，现在希望能做编排。
2.我们有有自建的定时任务调度管理服务，目前只想引入一个能做依赖管理，任务流调度的模块。
3.我们有自己的安全和审计考虑，所以管理数据源，追踪任务状态之类的工作都是要自己实现的或者改造到符合要求。包括告警，我们也需要走我们统一的告警通道。

所以我们更希望的形式是：
1.自建的定时调度服务负责任务流触发。
2.专门的服务负责依赖管理和子任务触发。
3.有一个客户端api抽象了跟服务端的通信，自定义的worker只要引入这个api即可具备任务流调度中worker的功能。

再次感谢EsSchduler的开源。

**Comment by lidongdai** [comment]
@yangjiajun2014 , 我们也计划对监控这块做的更详细，安全这块也有讨论，可以加个微信方便交流：510570367 

> 感谢，正在阅读。
> 
> 有以下几个考虑：
> 1.我们已经有很多long-running类型的任务，这些任务也基本上是插件化的，之前不支持编排，现在希望能做编排。
> 2.我们有有自建的定时任务调度管理服务，目前只想引入一个能做依赖管理，任务流调度的模块。
> 3.我们有自己的安全和审计考虑，所以管理数据源，追踪任务状态之类的工作都是要自己实现的或者改造到符合要求。包括告警，我们也需要走我们统一的告警通道。
> 
> 所以我们更希望的形式是：
> 1.自建的定时调度服务负责任务流触发。
> 2.专门的服务负责依赖管理和子任务触发。
> 3.有一个客户端api抽象了跟服务端的通信，自定义的worker只要引入这个api即可具备任务流调度中worker的功能。
> 
> 再次感谢EsSchduler的开源。
