### ISSUE TITLE
1.0.1版本启动api server报错java.lang.NoSuchFieldError: IS_SECURITY_ENABLED

### ISSUE THREAD

**Issue by hyperknob** [analysys/EasyScheduler#83]
如下所示，api-log打印如下：
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[ERROR] 2019-04-19 00:07:28.550 org.springframework.boot.SpringApplication:[839] - Application startup failed
java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
        at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:197)
        at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:422)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:892)

经过分析，把jasper-runtime-5.5.23.jar从lib中移除，api server则可以启动，应该是jar的问题，不知是什么依赖引用了此jar

**Comment by lidongdai** [comment]
jasper-runtime used by hive service,  details as follow:

![image](https://user-images.githubusercontent.com/48329107/56414173-5c189780-62bc-11e9-9cfa-9059244013aa.png)

**Comment by lidongdai** [comment]
we will closely pay attenation to the impact if remove this dependency ,If there is no impact, we will remove it in version 1.0.3

**Comment by samz406** [comment]
我这两天装了两次EasyScheduler，第一次是在centos上启动，api-server 可以启动，但是在ubuntu上启动就出现了上面的错误。

**Comment by lidongdai** [comment]
> 我这两天装了两次EasyScheduler，第一次是在centos上启动，api-server 可以启动，但是在ubuntu上启动就出现了上面的错误。

现在呢，解决了没？

**Comment by samz406** [comment]
> > 我这两天装了两次EasyScheduler，第一次是在centos上启动，api-server 可以启动，但是在ubuntu上启动就出现了上面的错误。
> 
> 现在呢，解决了没？

按照上面的老兄说的，删掉jar包。可以解决。
