### ISSUE TITLE
DAG图某些情况下可以画出环状图

### ISSUE THREAD

**Issue by lyf198972** [analysys/EasyScheduler#84]
复现方法，以SHELL节点为例：
1.拖4个shell节点，名称分别为s1,s2,s3,s4
2.连接方法：s1->s3 ; s2->s3; s3->s4 ;s4->s2 ; s4->s1

**Comment by mnikogit** [comment]
需要在生成dag的时候做有环检查

**Comment by lidongdai** [comment]
We've checked for loops in the generation of dag, but we haven't covered all the cases. We'll fix it in the next version.

**Comment by lenboo** [comment]
we will fix this bug in 1.0.2
