### ISSUE TITLE
node 使用版本是多少

### ISSUE THREAD

**Issue by woniulinux** [analysys/EasyScheduler#90]

**Comment by lidongdai** [comment]
8.9.4 , please refer to [build develop environment](https://analysys.github.io/easyscheduler_docs_cn/%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3.html#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
