### ISSUE TITLE
Can EasyScheduler support sub workflow task?

### ISSUE THREAD

**Issue by yangjiajun2014** [analysys/EasyScheduler#94]
We may need to combine workflows into one sometimes.Does/will easyscheduler support this feature?

**Comment by yangjiajun2014** [comment]
According to the desc,I think EasyScheduler  supports such feature.But I did not find the related code.Did I miss something?

**Comment by lidongdai** [comment]
@lenboo

**Comment by lenboo** [comment]
EasyScheduler support this feature by creating "SUB_PROCESS" task node which associated with processes. There are some code in "echeduler-dao/ProcessDao.java/createSubWorkProcessCommand()"
