### ISSUE TITLE
hive运行调度设置运行参数无法设置

### ISSUE THREAD

**Issue by zhuyizhizhi** [analysys/EasyScheduler#95]
![image](https://user-images.githubusercontent.com/42136195/56480783-3e327900-64ee-11e9-8e4d-d929b3e29b36.png)
这里hive需要设置运行参数，发现写在这里是无效的，请问怎么设置hive的运行参数呢

**Comment by lgcareer** [comment]
Please follow the Settings below
mapreduce.map.java.opts=-Xmx5120m;mapreduce.map.memory.mb=8000

**Comment by zhuyizhizhi** [comment]
> Please follow the Settings below
> mapreduce.map.java.opts=-Xmx5120m;mapreduce.map.memory.mb=8000

thank u～
